"""Patient and operational metric calculation."""
import numpy as np
def calculate_metrics(patients, events, history, busy, resources, end, closing):
    """Calculate safe scalar metrics for dashboard and comparison use."""
    arrived=patients[~patients.no_show]; complete=arrived[arrived.discharge_time.notna()]
    avg=lambda c: float(complete[c].mean()) if c in complete and complete[c].notna().any() else 0.
    pct=lambda c: float(np.percentile(complete[c].dropna(),90)) if c in complete and complete[c].notna().any() else 0.
    m={'total_patients_scheduled':len(patients),'total_patients_arriving':len(arrived),'no_show_patients':int(patients.no_show.sum()),'completed_patients':len(complete),'patients_unfinished_at_closing':int((arrived.discharge_time>closing).sum()),'patients_completing_after_closing':int((complete.discharge_time>closing).sum()),'average_first_doctor_wait':avg('first_doctor_wait'),'median_first_doctor_wait':float(complete.first_doctor_wait.median() or 0),'p90_first_doctor_wait':pct('first_doctor_wait'),'average_return_consultation_wait':avg('return_consultation_wait'),'median_return_consultation_wait':float(complete.return_consultation_wait.median() or 0),'p90_return_consultation_wait':pct('return_consultation_wait'),'average_total_waiting_time':avg('total_waiting_time'),'p90_total_waiting_time':pct('total_waiting_time'),'average_total_visit_duration':avg('total_time_in_clinic'),'average_final_satisfaction':avg('final_satisfaction_score'),'median_final_satisfaction':float(complete.final_satisfaction_score.median() or 0),'patients_below_satisfaction_60':int((complete.final_satisfaction_score<60).sum()),'percentage_below_60':float((complete.final_satisfaction_score<60).mean()*100) if len(complete) else 0,'maximum_combined_doctor_queue':max([x['length'] for x in history if x['queue'] in ('initial_consultation','return_consultation')],default=0)}
    for n in ['check_in','triage','doctors','laboratory','imaging']: m[f'{n}_utilisation']=min(1,busy[n]/max(1,end*getattr(resources,{'check_in':'check_in_staff','triage':'triage_nurses','doctors':'doctors','laboratory':'laboratory_capacity','imaging':'imaging_capacity'}[n])))
    m['percentage_waiting_periods_without_seat']=float(((complete.first_seat_available==False).sum()+(complete.return_seat_available==False).sum())/max(1,complete.first_seat_available.notna().sum()+complete.return_seat_available.notna().sum())*100); return m
