"""Patient record used by the simulation."""
from dataclasses import dataclass, field
from typing import Any
@dataclass
class Patient:
    patient_id: str; appointment_time: float; actual_arrival_time: float; early_or_late_minutes: float; no_show: bool = False; examination_type: str = "none"; initial_satisfaction_score: float = 80; final_satisfaction_score: float = 80; satisfaction_events: list[dict[str, Any]] = field(default_factory=list)
    first_check_in_start: float|None=None; first_check_in_end: float|None=None; triage_start: float|None=None; triage_end: float|None=None; first_doctor_queue_entry: float|None=None; initial_consultation_start: float|None=None; initial_consultation_end: float|None=None; examination_queue_entry: float|None=None; examination_start: float|None=None; examination_end: float|None=None; return_to_clinic_time: float|None=None; second_check_in_start: float|None=None; second_check_in_end: float|None=None; return_consultation_queue_entry: float|None=None; return_consultation_start: float|None=None; return_consultation_end: float|None=None; discharge_time: float|None=None; first_seat_available: bool|None=None; return_seat_available: bool|None=None
    def row(self) -> dict[str, Any]:
        d=self.__dict__.copy(); d['satisfaction_events']=str(d['satisfaction_events'])
        for name,a,b in [('first_check_in_wait','actual_arrival_time','first_check_in_start'),('triage_wait','first_check_in_end','triage_start'),('first_doctor_wait','first_doctor_queue_entry','initial_consultation_start'),('examination_wait','examination_queue_entry','examination_start'),('return_check_in_wait','return_to_clinic_time','second_check_in_start'),('return_consultation_wait','return_consultation_queue_entry','return_consultation_start')]: d[name]=None if d.get(a) is None or d.get(b) is None else d[b]-d[a]
        d['total_first_waiting_time']=sum(x or 0 for x in [d['first_check_in_wait'],d['triage_wait'],d['first_doctor_wait']]); d['total_return_waiting_time']=sum(x or 0 for x in [d['return_check_in_wait'],d['return_consultation_wait']]); d['total_examination_waiting_time']=d['examination_wait'] or 0; d['total_waiting_time']=d['total_first_waiting_time']+d['total_return_waiting_time']+d['total_examination_waiting_time']; d['total_time_in_clinic']=None if d['discharge_time'] is None else d['discharge_time']-d['actual_arrival_time']; return d
